Radio button alignment fixes and improvements
CenturyLink/ux-chi-uxpin-merge pull request #109
Opened 2022-09-20 01:00 UTC by soujanreddy

2022-09-29 08:18 UTC, josecarlosgonzalezv requested changes
On line 40 you have `Array(11).fill()`, please make 11 a constant.

2022-09-29 08:18 UTC, josecarlosgonzalezv commented on src/components/Radio/Radio.js
> +            <div className={this.props.inline ? `${FORM_CLASSES.ITEM} ${INLINE_CLASS}` : 'chi-col -w--12 -mb--1'} key={`radio-${i}`}>
We have already defined some of these utility classes.

```suggestion
            <div className={this.props.inline ? `${FORM_CLASSES.ITEM} ${INLINE_CLASS}` : `${UTILITY_CLASSES.COLUMN} ${UTILITY_CLASSES.MARGIN.BOTTOM[1]} -w--12`} key={`radio-${i}`}>
```

2022-09-29 08:18 UTC, josecarlosgonzalezv commented on src/components/Radio/Radio.js
> +        <div className={`${LABEL_CLASSES.LABEL}`}>
You can do this with similar cases.

```suggestion
        <div className={LABEL_CLASSES.LABEL}>
```

2022-09-29 08:18 UTC, josecarlosgonzalezv commented on src/components/Radio/Radio.js
> +          : <div className="chi-col -w--12 -mb--1">
Use the defined utility classes.

2022-09-29 08:18 UTC, josecarlosgonzalezv commented on src/components/Radio/Radio.js
> +            </div>}
`</div>}` is strange, could you format the whole file to see if you can fix it?

2022-09-30 10:27 UTC, jllr approved these changes

2022-09-30 10:27 UTC, josecarlosgonzalezv approved these changes

2022-09-30 10:28 UTC, merged