FSDE-29965-Add clickable bubble for Alert component
CenturyLink/ux-chi-uxpin-merge pull request #116
Opened 2022-11-20 21:09 UTC by soujanreddy

2022-11-23 14:55 UTC, josecarlosgonzalezv approved these changes

2022-11-25 08:16 UTC, josecarlosgonzalezv requested changes

2022-11-25 08:16 UTC, josecarlosgonzalezv commented on src/components/Alert/Alert.js
> +    this._setIconAndText();
```suggestion

```

2022-11-25 08:16 UTC, josecarlosgonzalezv commented on src/components/Alert/Alert.js
> +    return <div ref={this.props.uxpinRef}>{this._alert()}</div>;
```suggestion
    this._setIconAndText();
        
    return <div ref={this.props.uxpinRef}>{this._alert()}</div>;
```

2022-11-25 08:16 UTC, josecarlosgonzalezv commented on src/components/Alert/Alert.js
> +        this.state.defaultIcon = 'danger';
```suggestion
        this.state.defaultIcon = 'circle-warning';
```

2022-11-29 13:26 UTC, jllr approved these changes

2022-11-29 13:27 UTC, josecarlosgonzalezv approved these changes

2022-11-29 13:27 UTC, merged