Fix picker width alignment and icon default message updates
CenturyLink/ux-chi-uxpin-merge pull request #129
Opened 2023-01-17 19:39 UTC by soujanreddy

2023-01-18 11:20 UTC, josecarlosgonzalezv requested changes

2023-01-18 11:20 UTC, josecarlosgonzalezv commented on src/constants/classes.js
> +  },
```suggestion
```

2023-01-19 17:04 UTC, josecarlosgonzalezv approved these changes

2023-01-19 17:47 UTC, jllr approved these changes

2023-01-19 17:47 UTC, merged