Updates for dropdown radio sync text and stat base to support only marketing icons.
CenturyLink/ux-chi-uxpin-merge pull request #133
Opened 2023-02-14 01:51 UTC by soujanreddy

2023-02-22 16:28 UTC, josecarlosgonzalezv requested changes

2023-02-22 16:28 UTC, josecarlosgonzalezv commented on package.json
> +    "push-dev": "uxpin-merge push --webpack-config ./webpack.config.js --wrapper ./src/components/UXPinWrapper/UXPinWrapper.js --token ${UXPIN_DEV_TOKEN} --tag 1.0.31",
```suggestion
    "push-dev": "uxpin-merge push --webpack-config ./webpack.config.js --wrapper ./src/components/UXPinWrapper/UXPinWrapper.js --token ${UXPIN_DEV_TOKEN} --tag 1.0.30",
```

2023-02-23 13:45 UTC, josecarlosgonzalezv commented on src/components/Alert/Alert.js
>    _setIconAndText() {
```suggestion

  // TODO: Change name to _setIcon()
  _setIconAndText() {
```

2023-02-23 13:46 UTC, jllr approved these changes

2023-02-23 13:47 UTC, merged