UxPin Merge - Backstop tests implementation
CenturyLink/ux-chi-uxpin-merge pull request #136
Opened 2023-03-15 23:03 UTC by soujanreddy

- Backstop tests setup implementation.
- Add backstop config reference images for Button and Alert components.
- Update packages versions which are now compatible with node version 18.

2023-04-05 09:51 UTC, dani-cl-madrid requested changes

2023-04-05 09:51 UTC, dani-cl-madrid commented on backstop_data/engine_scripts/puppet/interceptImages.js
This file is not used. The `imageStub.jpg` file is not use either. 
@soujanreddy

2023-04-11 10:38 UTC, jllr approved these changes

2023-04-11 10:38 UTC, josecarlosgonzalezv approved these changes

2023-04-11 11:10 UTC, dani-cl-madrid approved these changes

2023-04-11 11:12 UTC, merged