Implement layout field for radio component - Inline and vertical
CenturyLink/ux-chi-uxpin-merge pull request #143
Opened 2023-05-05 23:21 UTC by soujanreddy

2023-05-12 07:45 UTC, josecarlosgonzalezv requested changes

2023-05-12 07:45 UTC, josecarlosgonzalezv commented on src/components/Radio/Radio.js
> +        <div className="chi-col -w--12 -mb--1">
```suggestion
        <div className={`${UTILITY_CLASSES.COLUMN} -w--12 -mb--1`}>
```

2023-05-12 07:45 UTC, josecarlosgonzalezv commented on src/components/Radio/Radio.js
> +    const vertical = "chi-col -w--12 -mb--1";
```suggestion
    const vertical = `${UTILITY_CLASSES.COLUMN} ${UTILITY_CLASSES.MARGIN.BOTTOM[1]} -w--12`;
```

2023-05-12 07:45 UTC, josecarlosgonzalezv commented on src/constants/constants.js
> +export const CHI_VERSION = '5.31.0';
This will be push after the new Chi 5.32.0 release.

```suggestion
export const CHI_VERSION = '5.32.0';
```

2023-05-16 08:10 UTC, josecarlosgonzalezv approved these changes

2023-05-16 09:42 UTC, jllr approved these changes

2023-05-16 09:43 UTC, merged